version: '2'
services:
    angdemo-app:
        image: angdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angdemo-mysql:3306/angdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angdemo-mysql:
        extends:
            file: mysql.yml
            service: angdemo-mysql
